# This is a basic workflow to help you get started with Actions

name: Check license
on:
  workflow_dispatch: {}
  
env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  check-license:
    name: Check for Unity license
    runs-on: ubuntu-latest
    steps:
      - name: Fail - No license
        if: ${{ !startsWith(env.UNIT_LICENSE, '<') }}
        run: exit 1      
      
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0
