# This is a basic workflow to help you get started with Actions

name: Check license
on:
  workflow_dispatch: {}

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Activate
        uses: game-ci/unity-activate@v2.0.0

