# This is a basic workflow to help you get started with Actions

name: Check license
on:
  workflow_dispatch: {}
  
env:
  TEST_SECRET: ${{ secrets.TEST_SECRET }}

jobs:
  check-license:
    name: Check for Unity license
    runs-on: ubuntu-latest
    steps:
      - name: Print env
        run: echo env.TEST_SECRET
      
      - name: Fail - No license
        if: ${{ !startsWith(env.TEST_SECRET, '<') }}
        run: exit 1      
      
      #- name: Unity - Activate
      #  uses: game-ci/unity-activate@v2.0.0
