name: Run Tests
on:    
  workflow_dispatch: {}

jobs:
  run-tests:
    name: Test all modes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        
      - name: Cache
        uses: actions/cache@v3.0.2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
        
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v2.0.2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
